import Link from 'next/link';
import React from 'react';

const TermsandConditionsSection = () => {
    return (
        <div className='privacy-area pt-110 pb-20'>
            <div className='container'>
                <div className="row">
                    <div className="col-12">
                        <div className="privacy-wrapper">
                            <p>We request our customers to thoroughly go through our terms of services and usage before signing up for our FTTH broadband plans. We reserve the right to modify, delete, update or add to any or all sections of this policy and our terms and conditions including terms of service anytime, with or without prior intimation. Customers are therefore requested to go through these from time to time. </p>
                            <div className="privacy-wrapper-box">
                                {/* <h5>1. Service Cancellation and Refunds</h5> */}
                                <p> We provide services in accordance with the registered plan on our website. Any interruptions in service are to be reported immediately by our customers to their service representatives for accelerated resolution. </p>
                                <p>Broadband speeds and bandwidth will be based on the terms of the plan selected by you during the registration process, and in case you want to modify this, you are requested to get in touch with our service representatives Bills incurred by the use of our services will be generated by the 15th of every month and invoiced to you. </p>
                                <p>In case of any queries, you are requested to contact our customer service personnel Our ground staff will provide you technical services to the best of our abilities, but we are not deemed to be liable for failure to do so owing to reasons beyond our control If for any reason, the ground inspection is not favorable for providing our services, we will provide you a full refund of the installation charges within 15 working days. </p>
                            </div>
                            <div className="privacy-wrapper-box">
                                {/* <h5>2. Non-Refundable Charges</h5>
                                <p><strong>Certain charges are non-refundable, and the following items are not eligible for a refund : </strong></p> */}
                                <p>Invoices will have to be paid on or before the due date and failure to do so would incur penal charges or late fee. We also reserve the right to discontinue the provision of our services if we deem it necessary. </p>
                                {/* <p>b. Fees associated with the purchase or rental of equipment.</p>
                                <p>c. Installation charges or fees paid to third-party contractors.</p>
                                <p>d. Any charges related to additional services or upgrades.</p>
                                <p>e. Fees for any domain registrations or other domain-related services.</p> */}
                            </div>
                            <div className="privacy-wrapper-box">
                                <h5>You can pay us by any of the following methods:</h5>
                                <p>Credit cards</p>
                                <p>Debit cards</p>
                                <p>Standing instructions on your bank account</p>
                                <p>Payment through cheque</p>
                                <p>Demand draft</p>
                                <p>Cash at our brand office</p>
                                <p>
                                    <strong>Online payment through NEFT or IMPS clearance Through phone banking Payments by way of cheques, pay orders, or demand drafts will have to be made at National Capital Region of Delhi made in favor of Praction Account Number – -xxxx in xxx bank. </strong>
                                </p>
                            </div>
                            <div className="privacy-wrapper-box">
                                {/* <h5>4. Refund Disputes</h5> */}
                                <p>We do not accept any outstation cheques and any such cheques addressed to us will be returned to the customer’s registered address for communication. A charge of Rs.150 shall be levied for postage and communication along with late fee charges incurred, if any..</p>
                            </div>
                            {/* <div className="privacy-wrapper-box">
                                <h5>5. Changes to the Refund Policy</h5>
                                <p>Netbox reserves the right to modify or update this Refund Policy at any time without prior notice. The updated policy will be effective immediately upon posting on our website. We encourage you to review this policy periodically to stay informed about any changes.</p>
                            </div>
                            <div className="privacy-wrapper-box">
                                <h5>6. Contact Us</h5>
                                <p>If you have any questions, concerns, or requests regarding this Privacy & Policy, please contact us at
                                    <Link href="mailto:netbox@gmail.com" className='hover-underline'> netbox@gmail.com</Link>.</p>
                            </div> */}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default TermsandConditionsSection;